import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/shared/Navbar';
import Banner from '@/components/shared/Banner';

const josefinSans = Josefin_Sans({
  variable: '--font-josefin-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${josefinSans.variable} antialiased bg-gray-800 text-white`}
      >
        <Navbar />
        <Banner />
        <div className='max-width-7xl mx-auto'>{children}</div>
      </body>
    </html>
  );
}
